package io.matel.app.domain;

public enum EventType {
    MIN_ADV, MIN_ADV_CANCEL, MIN_DETECT, MIN_DETECT_CANCEL, MIN_CONFIRM, MIN_CONFIRM_CANCEL, MAX_ADV, MAX_ADV_CANCEL, MAX_DETECT, MAX_CONFIRM, MAX_DETECT_CANCEL,
    MAX_CONFIRM_CANCEL, BUYERS ,SELLERS, NONE, ENTRY_LONG_ONLY, EXIT_LONG_ONLY, ENTRY_SHORT_ONLY, EXIT_SHORT_ONLY
}
